
//package my.TicTacToe;

import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;


public class TicTacToe extends javax.swing.JFrame {

    int count = 1;

    int flag1 = 0;
    int flag2 = 0;
    int flag3 = 0;
    int flag4 = 0;
    int flag5 = 0;
    int flag6 = 0;
    int flag7 = 0;
    int flag8 = 0;
    int flag9 = 0;

    int [][] game = new int[3][3];


    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic-Tac-Toe");

        jButton1.setText("Button 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1(evt);
            }
        });

        jButton2.setText("Button 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2(evt);
            }
        });

        jButton3.setText("Button 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3(evt);
            }
        });

        jButton4.setText("Button 4");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4(evt);
            }
        });

        jButton5.setText("Button 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5(evt);
            }
        });

        jButton6.setText("Button 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6(evt);
            }
        });

        jButton7.setText("Button 7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7(evt);
            }
        });

        jButton8.setText("Button 8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8(evt);
            }
        });

        jButton9.setText("Button 9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9(evt);
            }
        });

        jButton10.setText("Exit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("New Game");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1
        // TODO add your handling code here:

       if(flag1 == 0){
            if (count % 2 == 1){
                jButton1.setText("1");
                Check(0,0,1);
                flag1 = 1;
            }else{
                jButton1.setText("2");
                Check(0,0,2);
                flag1 = 1;
            }
            count ++;
        }

    }//GEN-LAST:event_Button1

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

      System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void Button2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2
        // TODO add your handling code here:

        if(flag2 == 0){
            if (count % 2 == 1){
                jButton2.setText("1");
                Check(0,1,1);
                flag2 = 1;
            }else{
                jButton2.setText("2");
                Check(0,1,2);
                flag2 = 1;
            }
            count ++;
        }

    }//GEN-LAST:event_Button2

    private void Button3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3
        // TODO add your handling code here:

        if(flag3 == 0){
            if (count % 2 == 1){
                jButton3.setText("1");
                Check(0,2,1);
                flag3 = 1;
            }else{
                jButton3.setText("2");
                Check(0,2,2);
                flag3 = 1;
            }
            count ++;
        }
    }//GEN-LAST:event_Button3

    private void Button4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4
        // TODO add your handling code here:

        if(flag4 == 0){
            if (count % 2 == 1){
                jButton4.setText("1");
                Check(1,0,1);
                flag4 = 1;
            }else{
                jButton4.setText("2");
                Check(1,0,2);
                flag4 = 1;
            }
            count ++;
        }
    }//GEN-LAST:event_Button4

    private void Button5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5
        // TODO add your handling code here:

        if(flag5 == 0){
            if (count % 2 == 1){
                jButton5.setText("1");
                Check(1,1,1);
                flag5 = 1;
            }else{
                jButton5.setText("2");
                Check(1,1,2);
                flag5 = 1;
            }
            count ++;
        }
    }//GEN-LAST:event_Button5

    private void Button6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6
        // TODO add your handling code here:

        if(flag6 == 0){
            if (count % 2 == 1){
                jButton6.setText("1");
                Check(1,2,1);
                flag6 = 1;
            }else{
                jButton6.setText("2");
                Check(1,2,2);
                flag6 = 1;
            }
            count ++;
        }
    }//GEN-LAST:event_Button6

    private void Button7(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7
        // TODO add your handling code here:

        if(flag7 == 0){
            if (count % 2 == 1){
                jButton7.setText("1");
                Check(2,0,1);
                flag7 = 1;
            }else{
                jButton7.setText("2");
                Check(2,0,2);
                flag7 = 1;
            }
            count ++;
        }
    }//GEN-LAST:event_Button7

    private void Button8(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8
        // TODO add your handling code here:

        if(flag8 == 0){
            if (count % 2 == 1){
                jButton8.setText("1");
                Check(2,1,1);
                flag8 = 1;
            }else{
                jButton8.setText("2");
                Check(2,1,2);
                flag8 = 1;
            }
            count ++;
        }
    }//GEN-LAST:event_Button8

    private void Button9(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9
        // TODO add your handling code here:

        if(flag9 == 0){
            if (count % 2 == 1){
                jButton9.setText("1");
                Check(2,2,1);
                flag9 = 1;
            }else{
                jButton9.setText("2");
                Check(2,2,2);
                flag9 = 1;
            }
            count ++;
        }
    }//GEN-LAST:event_Button9

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        count = 1;

        flag1 = 0;
        flag2 = 0;
        flag3 = 0;
        flag4 = 0;
        flag5 = 0;
        flag6 = 0;
        flag7 = 0;
        flag8 = 0;
        flag9 = 0;

        jButton1.setText("Button 1");
        jButton2.setText("Button 2");
        jButton3.setText("Button 3");
        jButton4.setText("Button 4");
        jButton5.setText("Button 5");
        jButton6.setText("Button 6");
        jButton7.setText("Button 7");
        jButton8.setText("Button 8");
        jButton9.setText("Button 9");

        for(int i = 0; i<3; i++){
            for(int j = 0; j<3; j++){
                game[i][j] = 0;
            }
        }



    }//GEN-LAST:event_jButton11ActionPerformed

    private void Check (int positionI, int positionJ, int player){

        game[positionI][positionJ] = player;

        Player1();
        Player2();
        Draw();


    }
    private void Player1 (){

        int win = 0;

        if((game[0][0] == 1) && (game[0][1] == 2) && (game[0][2] == 1)){
            win = 1;
        }else if((game[1][0] == 1) && (game[1][1] == 2) && (game[1][2] == 1)){
            win = 1;
        }else if((game[2][0] == 1) && (game[2][1] == 2) && (game[2][2] == 1)){
            win = 1;
        }else if((game[0][0] == 1) && (game[1][0] == 2) && (game[2][0] == 1)){
            win = 1;
        }else if((game[0][1] == 1) && (game[1][1] == 2) && (game[2][1] == 1)){
            win = 1;
        }else if((game[0][2] == 1) && (game[1][2] == 2) && (game[2][2] == 1)){
            win = 1;
        }else if((game[0][0] == 1) && (game[1][1] == 2) && (game[2][2] == 1)){
            win = 1;
        }else if((game[0][2] == 1) && (game[1][1] == 2) && (game[2][0] == 1)){
            win = 1;
        }

        if(win == 1){

            JFrame frame = new JFrame();
            frame.setTitle("Winner");
            frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            frame.setSize(400,600);
            JLabel labell = new JLabel("Player 1 Wins.",JLabel.CENTER);
            labell.setFont(new java.awt.Font("Arial", Font.BOLD, 25));
            frame.add(labell);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);

        }
    }

    private void Player2 (){

        int win = 0;

        if((game[0][0] == 2) && (game[0][1] == 1) && (game[0][2] == 2)){
            win = 1;
        }else if((game[1][0] == 2) && (game[1][1] == 1) && (game[1][2] == 2)){
            win = 1;
        }else if((game[2][0] == 2) && (game[2][1] == 1) && (game[2][2] == 2)){
            win = 1;
        }else if((game[0][0] == 2) && (game[1][0] == 1) && (game[2][0] == 2)){
            win = 1;
        }else if((game[0][1] == 2) && (game[1][1] == 1) && (game[2][1] == 2)){
            win = 1;
        }else if((game[0][2] == 2) && (game[1][2] == 1) && (game[2][2] == 2)){
            win = 1;
        }else if((game[0][0] == 2) && (game[1][1] == 1) && (game[2][2] == 2)){
            win = 1;
        }else if((game[0][2] == 2) && (game[1][1] == 1) && (game[2][0] == 2)){
            win = 1;
        }

        if(win == 1){

            JFrame frame = new JFrame();
            frame.setTitle("Winner");
            frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            frame.setSize(400,600);
            JLabel labell = new JLabel("Player 2 Wins.",JLabel.CENTER);
            labell.setFont(new java.awt.Font("Arial", Font.BOLD, 25));
            frame.add(labell);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);

        }

    }

    private void Draw(){

        if((game[0][0] != 0) && (game[0][1] != 0) &&(game[0][2] != 0) &&(game[1][0] != 0) &&(game[1][1] != 0) &&(game[1][2] != 0) &&(game[2][0] != 0) &&(game[2][1] != 0) &&(game[2][2] != 0)){

            JFrame frame = new JFrame();
            frame.setTitle("Draw");
            frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            frame.setSize(400,600);
            JLabel labell = new JLabel("Game is a Draw.",JLabel.CENTER);
            labell.setFont(new java.awt.Font("Arial", Font.BOLD, 25));
            frame.add(labell);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {


                new TicTacToe().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
